wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: ignite
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717618713
    t:
      1:
      - 1
      - 10
      - 55
      2:
      - 1
      - 10
      - 55
      3:
      - 23
      - 61
      4: 3.11.7
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
